apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aetherline

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - kafka.yaml
  - order-db.yaml
  - inventory-db.yaml
  - payment-db.yaml
  - notification-db.yaml
  - order-service.yaml
  - order-consumer.yaml
  - inventory-service.yaml
  - inventory-consumer.yaml
  - payment-service.yaml
  - payment-consumer.yaml
  - notification-service.yaml
  - notification-consumer.yaml
  - api-gateway.yaml
  - hpa-order-service.yaml
  - hpa-inventory-service.yaml
